### ISSUE TITLE
Key shortcuts do not show up in the main screen

### ISSUE THREAD

**Issue by Hunter-Github** [golbin/git-commander#13]
Key shortcuts do not show up.

**Comment by golbin** [comment]
It has some of shortcuts in the main screen. Could you please give me more details what is needed more?

**Comment by Hunter-Github** [comment]
Your GIF shows some shortcuts in gray font before labels(":COMMIT, :RESET" etc.). These do not show up on my computer.

**Comment by golbin** [comment]
Oh I see.That's an terminal ansi problem. You can fix it with changing your color schema of your terminal.(Try default terminal) However, I'll try to solve this.

**Comment by JSn1nj4** [comment]
I also have this issue on Windows (both Command Prompt and Git Bash). This is my first time trying Git Commander, and I do like the idea of it. Out of curiosity, what OS are you developing on?

Also, I did see what you said to @Hunter-Github. Will look into how I can make do on my end.

Lastly, here's some info about my setup: 
- OS: Windows 8.1
- node: 0.12.7
- npm: 2.11.3
- git-commander: 0.0.5

![first-try](https://cloud.githubusercontent.com/assets/5084820/8680069/e0ac7510-2a2c-11e5-838d-7c9a1e670e35.png)

**Comment by Hunter-Github** [comment]
Thanks, working fine now!

**Comment by golbin** [comment]
@Hunter-Github Thanks too. :+1:
