### ISSUE TITLE
win 7 한글 사용자를 위한 팁이 문서화 가 필요 할 것 같습니다.

### ISSUE THREAD

**Issue by zeroxy** [golbin/git-commander#29]
한글 파일명에 대한 가이드로 사용 전에 git 설정을 
git config --global core.quotepath false 
가 필요하다는 점.

nodejs 0.12 이상 버전이 필요하다는 점이 명시 되었으면 좋겠습니다

**Comment by golbin** [comment]
한글 파일명에 대한 부분은 생각지도 못했는데.. OTL;; 해당 옵션은 처음 알았네요. nodejs 버전은 packages.json 의 engines 에 넣어두긴 했는데, README 에 기재해두는게 좋겠군요.

README 어떤 섹션으로 넣을지 고민해봐야겠어요. 감사합니다. :smile:

**Comment by golbin** [comment]
관련 내용 작성했습니다. https://github.com/golbin/git-commander/commit/2ca32c267f4b38b9b181168a50630cc8b0b75c4e
