### ISSUE TITLE
Log message with 'commit' fail to show log

### ISSUE THREAD

**Issue by hugosenari** [golbin/git-commander#34]
Hi, nice command. :)

Testing here I found some strange behavior when you has 'commit inicial' in log message.

TypeError: Cannot read property 'name' of undefined
    at /usr/lib/node_modules/git-commander/controller/log.js:59:48

```
      line = line + " {cyan-fg}<" + item.author.name + ">{/cyan-fg}";
```

author is undefined then I changed with:

```
      line = line + " {cyan-fg}<" + (item.author ? item.author.name : 'cu')  + ">{/cyan-fg}";
```

Now it works but with other strange effect, now I have one commit more with: 
'inicial' 'No message' 'NaN month' 'Cu' (hash, message, time, author)

So I can think that this problem is about how code split commits :-/

:)

**Comment by golbin** [comment]
Hi, thanks for feedback. It happens because of wrong parse logic. So, I fixed it instead of your patch. :smiley:

**Comment by hugosenari** [comment]
I reinstalled here.

Now is working, thanks.  :+1: 

That was not a 'patch', was an example to help (me) find and understand this problem  (please don't look in translator what 'cu' means in pt-br).

**Comment by golbin** [comment]
Great! Thanks! :smile:
