### ISSUE TITLE
Show branch name

### ISSUE THREAD

**Issue by stefanjudis** [golbin/git-commander#37]
Hey hey,

I just tried your project, and it looks nice. :bowtie: 

What I would find really helpful to see the actual branch name when using `git-commander`.

In our workflows we usually name the branches with e.g. github issue numbers and connect via '#' to the issue.

E.g.

```
Branch name: feature/123-some-feature
Commit Msg: #123 add something
```

Thanks. :)

**Comment by golbin** [comment]
Thanks. And showing branch name is the first priority. :-) Plz wait til this weekend.

**Comment by stefanjudis** [comment]
Woooohoooooo. Thanks. ;)

**Comment by golbin** [comment]
https://github.com/golbin/git-commander/commit/36ae7f5de3781453c4aaa1cb1ced912afbf418e2
