### ISSUE TITLE
Broken status display

### ISSUE THREAD

**Issue by forivall** [golbin/git-commander#40]
ANSI color codes are being displayed in the main view. I suspect it has something to do with my git config (`~/.gitconfig`) which contains

```
[color]
    # diff = always
    grep = always
    interactive = always
    status = always
    ui = auto
    branch = auto
    diff = auto
```

![screenshot from 2015-08-10 17-18-22](https://cloud.githubusercontent.com/assets/760204/9187332/1b03e948-3f84-11e5-9cd8-40f5a4902591.png)

**Comment by golbin** [comment]
Thanks. I think it has to be fixed.

**Comment by forivall** [comment]
Also, I can confirm that it's the gitconfig `color=always` setting; it works fine after commenting it out.

**Comment by golbin** [comment]
I see the codes again and manpage of git. And it's better just adding your tips in the README.md until we can find best solutions.
