### ISSUE TITLE
Cannot type the letter "q" in a commit message

### ISSUE THREAD

**Issue by TheSinding** [golbin/git-commander#46]
I'm closing the commit editor when I type "q" ..
It's an easy fix tho.

I did a hotfix for it, if you are interested.. I might not be the "correct" way of doing it, I just check if the entered key is q when I'm inside the editor view.

```javascript
    view.textarea.key(config.keys.common.quit, function(ch, key) {
      if (key.full === 'q') return;
      editor.hide();
    });
```

**Comment by TheSinding** [comment]
If you want it vim like, maybe consider using the "**:**\<command\>" style ?
I personally would like that :+1:

**Comment by golbin** [comment]
@TheSinding I like vim :-)

It's better to make vim mode than just adding some keys.
If you can make some patches for this, I'd like to merge them.

**Comment by Hawaiideveloper** [comment]
@TheSinding I wanted to checkin on this merge.  Did it happen?

**Comment by TheSinding** [comment]
I never merged my changes, sorry
